[2024-08-04T10:25:12.484+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: excel_to_oracle_dag.load_excel_to_oracle manual__2024-08-04T10:20:08.976426+00:00 [queued]>
[2024-08-04T10:25:12.491+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: excel_to_oracle_dag.load_excel_to_oracle manual__2024-08-04T10:20:08.976426+00:00 [queued]>
[2024-08-04T10:25:12.492+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2024-08-04T10:25:12.503+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_excel_to_oracle> on 2024-08-04 10:20:08.976426+00:00
[2024-08-04T10:25:12.509+0000] {standard_task_runner.py:57} INFO - Started process 298 to run task
[2024-08-04T10:25:12.512+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'excel_to_oracle_dag', 'load_excel_to_oracle', 'manual__2024-08-04T10:20:08.976426+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/excel_to_oracle_dag.py', '--cfg-path', '/tmp/tmp362h4871']
[2024-08-04T10:25:12.513+0000] {standard_task_runner.py:85} INFO - Job 30: Subtask load_excel_to_oracle
[2024-08-04T10:25:12.555+0000] {task_command.py:416} INFO - Running <TaskInstance: excel_to_oracle_dag.load_excel_to_oracle manual__2024-08-04T10:20:08.976426+00:00 [running]> on host 946f4e3979be
[2024-08-04T10:25:12.619+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='excel_to_oracle_dag' AIRFLOW_CTX_TASK_ID='load_excel_to_oracle' AIRFLOW_CTX_EXECUTION_DATE='2024-08-04T10:20:08.976426+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-04T10:20:08.976426+00:00'
[2024-08-04T10:25:12.630+0000] {base.py:73} INFO - Using connection ID 'Connection_bai_test' for task execution.
[2024-08-04T10:25:12.787+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/excel_to_oracle_dag.py", line 68, in load_excel_to_oracle
    cursor.execute(insert_sql, tuple(row))
cx_Oracle.DatabaseError: ORA-00917: missing comma
[2024-08-04T10:25:12.796+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=excel_to_oracle_dag, task_id=load_excel_to_oracle, execution_date=20240804T102008, start_date=20240804T102512, end_date=20240804T102512
[2024-08-04T10:25:12.808+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 30 for task load_excel_to_oracle (ORA-00917: missing comma; 298)
[2024-08-04T10:25:12.845+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-08-04T10:25:12.866+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
