[2024-08-03T17:24:18.224+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: excel_to_oracle_dag.load_excel_to_oracle manual__2024-08-03T17:19:15.177558+00:00 [queued]>
[2024-08-03T17:24:18.235+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: excel_to_oracle_dag.load_excel_to_oracle manual__2024-08-03T17:19:15.177558+00:00 [queued]>
[2024-08-03T17:24:18.236+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-08-03T17:24:18.236+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2024-08-03T17:24:18.237+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-08-03T17:24:18.254+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): load_excel_to_oracle> on 2024-08-03 17:19:15.177558+00:00
[2024-08-03T17:24:18.264+0000] {standard_task_runner.py:55} INFO - Started process 408 to run task
[2024-08-03T17:24:18.269+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'excel_to_oracle_dag', 'load_excel_to_oracle', 'manual__2024-08-03T17:19:15.177558+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/excel_to_oracle_dag.py', '--cfg-path', '/tmp/tmpomzz86ir']
[2024-08-03T17:24:18.275+0000] {standard_task_runner.py:83} INFO - Job 34: Subtask load_excel_to_oracle
[2024-08-03T17:24:18.349+0000] {task_command.py:376} INFO - Running <TaskInstance: excel_to_oracle_dag.load_excel_to_oracle manual__2024-08-03T17:19:15.177558+00:00 [running]> on host 76baa70b3a2a
[2024-08-03T17:24:18.428+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=excel_to_oracle_dag
AIRFLOW_CTX_TASK_ID=load_excel_to_oracle
AIRFLOW_CTX_EXECUTION_DATE=2024-08-03T17:19:15.177558+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-08-03T17:19:15.177558+00:00
[2024-08-03T17:24:18.430+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/excel_to_oracle_dag.py", line 44, in load_excel_to_oracle
    connection = cx_Oracle.connect(user=ORACLE_USER, password=ORACLE_PASSWORD, dsn=dsn)
cx_Oracle.DatabaseError: DPI-1047: Cannot locate a 64-bit Oracle Client library: "libclntsh.so: cannot open shared object file: No such file or directory". See https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html for help
[2024-08-03T17:24:18.442+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=excel_to_oracle_dag, task_id=load_excel_to_oracle, execution_date=20240803T171915, start_date=20240803T172418, end_date=20240803T172418
[2024-08-03T17:24:18.454+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 34 for task load_excel_to_oracle (DPI-1047: Cannot locate a 64-bit Oracle Client library: "libclntsh.so: cannot open shared object file: No such file or directory". See https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html for help; 408)
[2024-08-03T17:24:18.481+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-08-03T17:24:18.505+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
