[2024-08-04T10:00:42.949+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: excel_to_oracle_dag.load_excel_to_oracle manual__2024-08-04T10:00:41.486219+00:00 [queued]>
[2024-08-04T10:00:42.956+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: excel_to_oracle_dag.load_excel_to_oracle manual__2024-08-04T10:00:41.486219+00:00 [queued]>
[2024-08-04T10:00:42.957+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-08-04T10:00:42.969+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_excel_to_oracle> on 2024-08-04 10:00:41.486219+00:00
[2024-08-04T10:00:42.976+0000] {standard_task_runner.py:57} INFO - Started process 523 to run task
[2024-08-04T10:00:42.979+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'excel_to_oracle_dag', 'load_excel_to_oracle', 'manual__2024-08-04T10:00:41.486219+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/excel_to_oracle_dag.py', '--cfg-path', '/tmp/tmpp4zm7ium']
[2024-08-04T10:00:42.980+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask load_excel_to_oracle
[2024-08-04T10:00:43.029+0000] {task_command.py:416} INFO - Running <TaskInstance: excel_to_oracle_dag.load_excel_to_oracle manual__2024-08-04T10:00:41.486219+00:00 [running]> on host b230a9a3e87a
[2024-08-04T10:00:43.097+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='excel_to_oracle_dag' AIRFLOW_CTX_TASK_ID='load_excel_to_oracle' AIRFLOW_CTX_EXECUTION_DATE='2024-08-04T10:00:41.486219+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-04T10:00:41.486219+00:00'
[2024-08-04T10:00:43.108+0000] {base.py:73} INFO - Using connection ID 'Connection_bai_test' for task execution.
[2024-08-04T10:00:43.278+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/excel_to_oracle_dag.py", line 49, in load_excel_to_oracle
    excel_data = pd.ExcelFile(file_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1496, in __init__
    ext = inspect_excel_format(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1371, in inspect_excel_format
    with get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 868, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\airflow\\data test\\KPI_Template.xlsx'
[2024-08-04T10:00:43.289+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=excel_to_oracle_dag, task_id=load_excel_to_oracle, execution_date=20240804T100041, start_date=20240804T100042, end_date=20240804T100043
[2024-08-04T10:00:43.302+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 14 for task load_excel_to_oracle ([Errno 2] No such file or directory: 'C:\\airflow\\data test\\KPI_Template.xlsx'; 523)
[2024-08-04T10:00:43.352+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-08-04T10:00:43.369+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
